import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Cormorant } from "next/font/google";
import { Spicy_Rice } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";
import { ConvexClientProvider } from "@/components-multiplayer/ConvexClientProvider";
import NextProvider from "./next-provider";
import MusicPlayer from "./multiplayer/music/background-music";
import background from "@/public/assets/images/background.png";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });
const cormorant = Cormorant({ subsets: ["latin"] });
const spicy_rice = Spicy_Rice({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cormorant.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ConvexClientProvider>
            <NextProvider>
              <div className="absolute inset-0">
                <Image
                  alt="Mountains"
                  src={background}
                  placeholder="blur"
                  quality={100}
                  fill
                  sizes="100vw"
                  style={{
                    objectFit: "cover",
                  }}
                />
                <div className="absolute inset-0 bg-gradient-to-r from-black via-transparent to-transparent opacity-100" />
              </div>

              {/* Music Player */}
              <MusicPlayer />

              {children}
            </NextProvider>
          </ConvexClientProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
